title: Kuo Liu, PhD
description: Kuo Liu's personal page

url: http://localhost:4000
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: About
      url: /about
    - title: Blog
      url: /index.html
    - title: Contact
      url: /contact

social:
    github: kuol
    twitter: liukuo99
    email: liukuo99@gmail.com
    linkedin: kuo-liu-7b3b1a3b

google_analytics: "UA-58263416-1"

disqus:
    shortname: liukuo99
